services:
  todo-db:
    image: diamol/postgres:2e-12
    ports:
      - "5433:5432"
    networks:
      - app-net

  todo-web:
    image: diamol/ch06-todo-list:2e
    ports:
      - "8030:8080"
    environment:
      - Database:Provider=Postgres
    depends_on:
      - todo-db
    networks:
      - app-net
    secrets:
      - source: postgres-connection
        target: C:\app\config\

networks:
  app-net:
    external:
      name: nat

secrets:
  postgres-connection:
    file: ./config/
